const Routes = {
    WELCOME: 'Welcome',
    ONBOARDING: 'Onboarding',
    GET_STARTED: 'GetStarted',
    LOGIN: 'Login',
    SIGN_UP: 'SignUp',
    SET_PASSWORD: 'SetPassword',
    VERIFY_EMAIL: 'VerifyEmail',
    VERIFY_PHONE: 'VerifyPhone',
    FORGET_PASSWORD: 'ForgetPassword',
    CREATE_NEW_PASSWORD: 'CreateNewPassword',
    PASSWORD_CHANGED: 'PasswordChanged',
    CHATS: 'Chats',
    CHAT: 'Chat',
    ADD_FRIEND: 'AddFriend',
    CREATE_GROUP: 'CreateGroup',
    PROFILE: 'Profile',
    MEDIA: 'Media',
    GROUP_MEMBERS: 'GroupMembers',
    PROFILE_MENU: 'ProfileMenu',
    TERMS: 'Terms',
    PRIVACY_POLICY: 'PrivacyPolicy',
    ABOUT_APP: 'AboutApp',
    CONTACT_SUPPORT: 'Contact&Support',
    FRIEND_PROFILE: 'FriendProfile',
    GROUP_PROFILE: 'GroupProfile',
    EDIT_GROUP: 'EditGroup',
    PROFILE_EDIT_SUCCESS: 'ProfileEditSuccess',
    MESSAGE_INFO: 'MessageInfo',
};

export default Routes;
